name: Auto-Build Data Prepper ARM64 Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read
  packages: write

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release tag from upstream
        id: get_version
        run: |
          tag=$(curl -s https://api.github.com/repos/opensearch-project/data-prepper/releases/latest | jq -r .tag_name)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Clone Data Prepper source at tag
        run: |
          git clone --depth 1 --branch "${{ steps.get_version.outputs.tag }}" https://github.com/opensearch-project/data-prepper.git dp-src

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Data Prepper distribution (executable jar)
        working-directory: ./dp-src
        run: ./gradlew :data-prepper-dist:shadowJar --no-daemon

      - name: Create Dockerfile
        run: |
          JAR_FILE=$(find dp-src/data-prepper-dist/build/libs -name "data-prepper-*-all.jar" | head -n 1)
          echo "Using JAR: $JAR_FILE"
          cat <<EOF > dp-src/Dockerfile
          FROM amazoncorretto:17-alpine
          RUN addgroup -S dataprepper && adduser -S dataprepper -G dataprepper
          WORKDIR /usr/share/data-prepper
          COPY $(basename $JAR_FILE) data-prepper.jar
          USER dataprepper
          CMD ["java", "-jar", "data-prepper.jar"]
          EOF
          cp "\$JAR_FILE" "dp-src/$(basename \$JAR_FILE)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: ./dp-src
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/techwavedev/data-prepper:arm64-${{ steps.get_version.outputs.tag }}
            ghcr.io/techwavedev/data-prepper:arm64-latest
