name: Build Data Prepper for ARM64

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (not pushed)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: false
          platforms: linux/arm64
          tags: data-prepper:arm64-dev
