name: Auto-Build Data Prepper ARM64 Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Daily at 03:00 UTC

permissions:
  contents: read
  packages: write

jobs:
  build-multiarch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU for ARM64 emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Retrieve latest release tag from upstream
        id: get_version
        run: |
          tag=$(curl -s https://api.github.com/repos/opensearch-project/data-prepper/releases/latest | jq -r .tag_name)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Clone Data Prepper source at specific tag
        run: |
          git clone --depth 1 --branch "${{ steps.get_version.outputs.tag }}" https://github.com/opensearch-project/data-prepper.git dp-src

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Data Prepper without tests
        working-directory: ./dp-src
        run: ./gradlew build -x test --no-daemon

      - name: Prepare Dockerfile and configuration
        run: |
          JAR_FILE=$(find dp-src -type f -name "data-prepper*.jar" | grep -v -e original -e sources | head -n 1)
          JAR_BASENAME=$(basename "$JAR_FILE")
          echo "Using JAR: $JAR_FILE"

          cat <<EOF > dp-src/Dockerfile
          FROM amazoncorretto:17-alpine
          RUN addgroup -S dataprepper && adduser -S dataprepper -G dataprepper
          WORKDIR /usr/share/data-prepper
          COPY ${JAR_BASENAME} ${JAR_BASENAME}
          RUN mkdir -p /usr/share/data-prepper/config
          USER dataprepper
          ENTRYPOINT ["java", "-jar", "${JAR_BASENAME}", "/usr/share/data-prepper/config/data-prepper-config.yaml"]
          EOF

          cp "$JAR_FILE" "dp-src/$JAR_BASENAME"

          mkdir -p dp-src/config
          cat <<EOF > dp-src/config/data-prepper-config.yaml
          ssl: false
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./dp-src
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/techwavedev/data-prepper:${{ steps.get_version.outputs.tag }}
            ghcr.io/techwavedev/data-prepper:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
